export const FETCH_PRODUCTS = "FETCH[PRODUCTS]";
export const FETCH_PRODUCT = "FETCH[PRODUCT]";
export const CATEGORY_PRODUCT = "FETCH[CATEGORY_PRODUCT]";
export const ADD_CART = "ADD[CART]";
export const REMOVE_CART = "REMOVE[CART]";
export const REMOVE_NUMBER_CART = "REMOVE[CART_NUMBER]";
